profile_img: /assets/img/profile_img.jpg
description: MATT-ARQSOFT

location_icon: /assets/icon/location_icon.png
location: Barcelona, Spain

linkedin_icon: /assets/icon/linkedin_icon.png
linkedin: Roger Aylagas
linkedin_link: https://www.linkedin.com/in/roger-aylagas-torres/

email_icon: /assets/icon/email_icon.png
email: mailto:rogeraylagas97@gmail.com

cv_icon: /assets/icon/cv_icon.png
cv: assets\docs\cv.pdf

show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
